### **Task 1**
* ***Question No.  1.1*** 

### ***Part(1.1(a))***
> manual solution

Let’s break down the given transformation matrix (A):
$$
[ A = \begin{bmatrix} 0 & -2 & 3 \ 2 & 0 & 1 \ 0 & 0 & 1 \end{bmatrix} ]
$$

We have the following relationship:
$$

[ \begin{bmatrix} x’ \ y’ \ 1 \end{bmatrix} = A \begin{bmatrix} x \ y \ 1 \end{bmatrix} ]
$$

To find the elements (x’) and (y’), we multiply the matrix (A) by the vector

$$
(\begin{bmatrix} x \ y \ 1 \end{bmatrix})
$$

$$
[ \begin{bmatrix} x’ \ y’ \ 1 \end{bmatrix} = \begin{bmatrix} 0 & -2 & 3 \ 2 & 0 & 1 \ 0 & 0 & 1 \end{bmatrix} \begin{bmatrix} x \ y \ 1 \end{bmatrix} ]
$$
Performing the matrix multiplication:
$$
[ x’ = 0 \cdot x + (-2) \cdot y + 3 \cdot 1 = -2y + 3 ] [ y’ = 2 \cdot x + 0 \cdot y + 1 \cdot 1 = 2x + 1 ]
$$
Therefore, the elements (x’) and (y’) in terms of (x) and (y) are:
$$
[ x’ = -2y + 3 ] [ y’ = 2x + 1 ]
$$


### ***Part(1.1(b))***
> python solution

In [23]:
import numpy as np

# Construct the transformation matrix A
A = np.array([[0, -2, 3], 
              [2, 0, 1],
              [0, 0, 1]])

# Define the input vector
v = np.array([4, 5, 1])
v_transposed = np.transpose(v)

# Perform matrix multiplication to transform the vector
v_transformed = np.dot(A, v_transposed)

print("Transformation matrix A:")
print(A)
print("\nInput vector v:")
print(v_transposed)
print("\nTransformed vector v':")
print(v_transformed)


Transformation matrix A:
[[ 0 -2  3]
 [ 2  0  1]
 [ 0  0  1]]

Input vector v:
[4 5 1]

Transformed vector v':
[-7  9  1]


### ***Part(1.1(c))***
> manual solution

Scaling Operation: Suppose we have a scaling factor (s_x) along the x-axis and a scaling factor (s_y) along the y-axis. The scaling matrix (S) is given by:
$$
 [ S =\begin{bmatrix} s_x & 0 & 0 \ 0 & s_y & 0 \ 0 & 0 & 1 \end{bmatrix} ]
 $$
  Applying this scaling matrix to the vector
$$ 
(\begin{bmatrix} x \ y \ 1 \end{bmatrix})
$$

 gives us:
$$
[ \begin{bmatrix} x’ \ y’ \ 1 \end{bmatrix} = S \begin{bmatrix} x \ y \ 1 \end{bmatrix} = \begin{bmatrix} s_x \cdot x \ s_y \cdot y \ 1 \end{bmatrix} ]
 $$
Shearing Operation: Suppose we have a shear factor (h_{xy}) that shears along the x-axis based on the y-coordinate. The shearing matrix (H) is given by: [ H =
$$
\begin{bmatrix} 1 & h_{xy} & 0 \ 0 & 1 & 0 \ 0 & 0 & 1 \end{bmatrix} ]
$$
 Applying this shearing matrix to the scaled vector 
$$
(\begin{bmatrix} s_x \cdot x \ s_y \cdot y \ 1 \end{bmatrix})
$$
gives us the final transformed vector:
$$ 
[ \begin{bmatrix} x’’ \ y’’ \ 1 \end{bmatrix} 
$$ = 
$$ H \begin{bmatrix} s_x \cdot x \ s_y \cdot y \ 1 \end{bmatrix}
$$ =
$$ \begin{bmatrix} s_x \cdot x + h_{xy} \cdot s_y \cdot y \ s_y \cdot y \ 1 \end{bmatrix} ]
$$

Combined Matrix (B): The combined transformation matrix (B) is obtained by multiplying the scaling matrix (S) with the shearing matrix (H):
$$ 
[ B = H \cdot S = \begin{bmatrix} 1 & h_{xy} & 0 \ 0 & 1 & 0 \ 0 & 0 & 1 \end{bmatrix} 
$$
$$
\begin{bmatrix} s_x & 0 & 0 \ 0 & s_y & 0 \ 0 & 0 & 1 \end{bmatrix} ]
$$ 
The resulting matrix (B) will have the combined effect of scaling and shearing on the vector 
$$(\begin{bmatrix} x \ y \ 1 \end{bmatrix}).$$

### ***Part(1.1(d))***
> python solution

In [24]:
import numpy as np

def apply_scaling_and_shearing(v, s, h):
    # Create the scaling matrix
    S = np.array([[s, 0], [0, s]])
    # Create the shearing matrix
    Hx = np.array([[1, h], [0, 1]])
    # Combine the transformations
    B = np.dot(S, Hx)
    # Apply the transformation to the input vector
    v_prime = np.dot(B, v)
    return v_prime

# Example usage
input_vector = np.array([4, 5, 1])
scaling_factor = 2
shearing_factor = 3.5
transformed_vector = apply_scaling_and_shearing(input_vector[:2], scaling_factor, shearing_factor)
print("Transformed vector:", transformed_vector)


Transformed vector: [43. 10.]


## ***Question 1.2***

### ***Part(1.2(a))***
> manual solution

Certainly! Let’s calculate the cofactor (C_{4,4}) of matrix (E).

Matrix (E) is given as:
[ E =
$$ 
\begin{bmatrix} 1 & 4 & -1 & 2 \ 2 & 0 & 8 & 8 \ 4 & -2 & 1 & 3 \ 0 & 0 & 0 & 1 \end{bmatrix} ]
$$
To find the cofactor (C_{4,4}), we follow these steps:

Calculate the Minor:

Remove the fourth row and fourth column from matrix (E).

The resulting submatrix (minor) is: 
$$
[ \text{Minor}_{4,4} = \begin{bmatrix} 1 & 4 & -1 \ 2 & 0 & 8 \ 4 & -2 & 1 \end{bmatrix} ]
$$ 
Apply the Checkerboard Pattern of Signs:

We alternate the signs in a checkerboard pattern, starting with a positive sign in the top-left corner.

So, the sign for (C_{4,4}) will be positive.

Calculate the Determinant of the Minor:

The determinant of the minor can be found using the formula: 
$$ 
[ \text{det}(\text{Minor}_{4,4}) = \begin{vmatrix} 1 & 4 & -1 \ 2 & 0 & 8 \ 4 & -2 & 1 \end{vmatrix} ]
$$ 
Evaluating the determinant:
$$ [ \text{det}(\text{Minor}_{4,4}) = 1 \cdot \begin{vmatrix} 0 & 8 \ -2 & 1 \end{vmatrix} - 
$$
$$
4 \cdot \begin{vmatrix} 2 & 8 \ 4 & 1 \end{vmatrix} - 
$$
$$
(-1) 
 
\cdot \begin{vmatrix} 2 & 0 \ 4 & -2 \end{vmatrix} ]
$$
$$
[ = 1 \cdot (0 \cdot 1 - 8 \cdot (-2)) - 4 \cdot (2 \cdot 1 - 8 \cdot 4) - (-1) \cdot (2 \cdot (-2) - 0 \cdot 4) ] [ = 1 \cdot (16) - 4 \cdot (-30) - (-1) \cdot (-4) = 16 + 120 + 4 = 140 ]
$$ 
Multiply by the Sign:
Since the sign for (C_{4,4}) is positive, 
$$ 
we have: [ C_{4,4} = (+1) \cdot \text{det}(\text{Minor}_{4,4}) = 140 ]
$$ 

### ***Part(1.2(b))***
> python solution

In [26]:
import numpy as np
from numpy.testing import assert_allclose

E = np.array([
    [1, 4, -1, 2],
    [2, 0, 8, 8],
    [4, -2, 1, 3],
    [0, 0, 0, 1]
])

E_inv = np.linalg.inv(E)


I = np.eye(4)

E_inv_E = np.dot(E_inv, E)

print("E_inv * E =", E_inv_E)
# Seting a tolerance value
tolerance = 1e-9

# Compare E_inv_E and I using assert_allclose
assert_allclose(E_inv_E, I, atol=tolerance)
tolerance = 1e-9

# Compare E_inv_E and I using np.allclose
is_equal = np.allclose(E_inv_E, I, atol=tolerance)

print("E_inv * E is equal to I within the tolerance:", is_equal)
print("E_inv * E == I:", np.allclose(E_inv_E, I))



E_inv * E = [[ 1.00000000e+00 -5.55111512e-17  0.00000000e+00  1.11022302e-16]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00 -1.11022302e-16]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00 -1.11022302e-16]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
E_inv * E is equal to I within the tolerance: True
E_inv * E == I: True


## ***Question 1.3***
> manual solution

**Reason 1**

The given matrix is a singular matrix because it has a determinant of zero. This means that the matrix is not invertible, and its inverse does not exist.
To understand why this matrix is singular, let's analyze its determinant:

| 1 0 0 |

| 0 1 0 |

| 0 0 0 |

| 0 0 0 |

| 0 0 0 |

| 0 0 0 |

| 0 0 1 |

- The determinant of the first three rows (the main diagonal) is zero. This means that there are two linearly dependent rows in the matrix

- The determinant of this matrix is the product of the diagonal elements, which is 0. This is because the matrix has a row of all zeros, which means that the determinant is zero.

- As a result, the matrix is singular, and it cannot be inverted. This means that the operation of projecting 3D pixels onto the 2D plane cannot be reversed, and the original 3D coordinates cannot be recovered from the 2D projection.
- In other words, the information about the z-coordinate (depth) is lost in the projection process, and the resulting 2D image does not contain enough information to reconstruct the original 3D model.

**Reason  2**

- The determinant of a 2x2 matrix is given by the formula (a*d) - (b*c), where a, b, c, and d are the matrix elements. In this case, a = 1, b = 0, c = 0, and d = 1. So, the determinant is:


(1 * 1) - (0 * 0) = 1 - 0 = 1


- However, the given operator is a 3x4 matrix, and the determinant is not defined for non-square matrices. Instead, we can consider the rank of the matrix, which is the size of the largest square submatrix with a non-zero determinant. In this case, the rank of the matrix is 2, as the submatrix formed by the first two rows and columns has a determinant of 1.

- Since the > ***rank of the matrix is less than its number of columns (2 < 4)***, the matrix is singular and cannot be inverted. This operation cannot be reversed because there is no unique solution for the original 3D coordinates given the 2D projection. In other words, multiple 3D points can be projected onto the same 2D point, making it impossible to recover the original 3D coordinates without additional information.

## ***Question 1.4***
### ***Part(1.4(a))***
> manual solution

To construct the 4x4 matrix G, let's first understand the given equations and what the unknowns 𝑎, 𝑏, 𝑐, 𝑑 represent.

Given the affine transformation matrix F:
$$
[ F = \begin{pmatrix} a & b \\ c & d \end{pmatrix} ]
$$
And the pairs of corresponding pixels:
$$
[ v_1 = \begin{pmatrix} x_1 \\ y_1 \end{pmatrix} \text{ and } v_1' = \begin{pmatrix} x_1' \\ y_1' \end{pmatrix} ]
$$
$$
[ v_2 = \begin{pmatrix} x_2 \\ y_2 \end{pmatrix} \text{ and } v_2' = \begin{pmatrix} x_2' \\ y_2' \end{pmatrix} ]
$$

We have the following simultaneous equations:

$$
a x_1 + b y_1 = x_1' \\ c x_1 + d y_1 = y_1' \\ a x_2 + b y_2 = x_2' \\ c x_2 + d y_2 = y_2']
$$

Now, let's rewrite these equations in matrix form:
$$
G = \left[ \begin{array}{cccc}
x_1 & y_1 & 0 & 0 \\
0 & 0 & x_1 & y_1 \\
x_2 & y_2 & 0 & 0 \\
0 & 0 & x_2 & y_2 \\
\end{array} \right]
\left[ \begin{array}{c}
a \\
b \\
c \\
d \\
\end{array} \right]
=
\left[ \begin{array}{c}
x_1' \\
y_1' \\
x_2' \\
y_2' \\
\end{array} \right]
$$





Which can be simplified to:
$$
\begin{pmatrix}
G & \begin{pmatrix} a \\ b \\ c \\ d \end{pmatrix} = \begin{pmatrix} x_1' \\ y_1' \\ x_2' \\ y_2' \end{pmatrix}
\end{pmatrix}
$$
From this, we can see that the 4x4 matrix G is constructed by arranging the pixel coordinates accordingly.


***So, the matrix G is:***
\[ G = 
\begin{pmatrix} 
x_1 & y_1 & 0 & 0 \\ 
0 & 0 & x_1 & y_1 \\ 
x_2 & y_2 & 0 & 0 \\ 
0 & 0 & x_2 & y_2 
\end{pmatrix}
\]
This matrix G represents the linear system of equations that relates the unknown coefficients of the affine transformation to the pixel coordinates.


### ***Part(1.4(b))***

To solve for the first unknown coefficient \( a \), we can use Cramer's Rule, which states that if we have a system of linear equations represented by \( Ax = b \), where \( A \) is the coefficient matrix, \( x \) is the vector of unknowns, and \( b \) is the vector of constants, then the solution for \( x_i \) (the \( i \)-th unknown) can be found using the formula:
$$
x_i = \frac{{\text{det}(A_i)}}{{\text{det}(A)}} 
$$

where \( A_i \) is the matrix obtained by replacing the \( i \)-th column of \( A \) with the vector \( b \), and \( \text{det} \) denotes the determinant.

In our case, we have the system:

\[
\begin{cases}
a \cdot x_1 + b \cdot y_1 = x_1' \\
c \cdot x_1 + d \cdot y_1 = y_1' \\
a \cdot x_2 + b \cdot y_2 = x_2' \\
c \cdot x_2 + d \cdot y_2 = y_2'
\end{cases}
\]


Let's denote \( D \) as the determinant of matrix \( G \), \( D_a \) as the determinant of \( G \) with the first column replaced by \( (x_1', y_1', x_2', y_2')^T \), and \( D_b, D_c, D_d \) similarly.

Then, using Cramer's Rule, we have:
$$
a = \frac{{D_a}}{{D}}
$$

where:
$$
D_a = \begin{vmatrix}
x_1' & y_1' & 0 & 0 \\
0 & 0 & x_1 & y_1 \\
x_2' & y_2' & 0 & 0 \\
0 & 0 & x_2 & y_2 \\
\end{vmatrix}
$$

$$
D_b = \begin{vmatrix}
x_1 & y_1 & 0 & 0 \\
x_1' & y_1' & 0 & 0 \\
x_2 & y_2 & 0 & 0 \\
x_2' & y_2' & 0 & 0 \\
\end{vmatrix}
$$

$$
D_c = \begin{vmatrix}
x_1 & y_1 & x_1' & y_1' \\
0 & 0 & x_1 & y_1 \\
x_2 & y_2 & x_2' & y_2' \\
0 & 0 & x_2 & y_2 \\
\end{vmatrix}
$$

$$
D_d = \begin{vmatrix}
x_1 & y_1 & 0 & 0 \\
0 & 0 & x_1 & y_1 \\
x_2 & y_2 & 0 & 0 \\
x_2' & y_2' & 0 & 0 \\
\end{vmatrix}
$$

We can then plug these determinants into the formula to solve for \( a \).

To solve for the value of \(a\), we can use Cramer's Rule, which states:

$$
a = \frac{{D_a}}{{D}}
$$


where \(D_a\) is the determinant of the matrix \(G\) with the first column replaced by the vector \((x_1', y_1', x_2', y_2')^T\), and \(D\) is the determinant of the original matrix \(G\).

Let's compute \(D_a\) and \(D\) using the provided matrices:

Given:

$$
G = \begin{pmatrix}
x_1 & y_1 & 0 & 0 \\
0 & 0 & x_1 & y_1 \\
x_2 & y_2 & 0 & 0 \\
0 & 0 & x_2 & y_2 \\
\end{pmatrix}
$$

$$
D_a = \begin{vmatrix}
x_1' & y_1' & 0 & 0 \\
0 & 0 & x_1 & y_1 \\
x_2' & y_2' & 0 & 0 \\
0 & 0 & x_2 & y_2 \\
\end{vmatrix} 
$$

$$
D = \begin{vmatrix}
x_1 & y_1 & 0 & 0 \\
0 & 0 & x_1 & y_1 \\
x_2 & y_2 & 0 & 0 \\
0 & 0 & x_2 & y_2 \\
\end{vmatrix}
$$

Now, let's compute the determinants:

$$
 D_a = (x_1' \cdot (0 \cdot 0 - 0 \cdot 0) - y_1' \cdot (0 \cdot 0 - 0 \cdot 0)) - (0 \cdot ((0 \cdot y_1) - (x_1 \cdot 0)) - 0 \cdot ((x_2 \cdot y_2) - (y_2 \cdot x_2))) 
$$

$$
D = (x_1 \cdot (0 \cdot 0 - 0 \cdot 0) - y_1 \cdot (0 \cdot 0 - 0 \cdot 0)) - (0 \cdot ((0 \cdot y_1) - (x_1 \cdot 0)) - 0 \cdot ((x_2 \cdot y_2) - (y_2 \cdot x_2)))
$$

Then, substitute these determinants into the formula for \(a\):

$$
a = \frac{{D_a}}{{D}}
$$

Since both _**D_a and D are zero**_, we cannot find a meaningful value for \(a\) using Cramer's Rule. This indicates that the system of equations may not have a unique solution or that further analysis is needed.

## ***Task 2***


* ***Question No.  2.1***
  ### ***Part(2.1(a))***
  > Manual solution

2.1a, we need to create formulas for the expectation value of the mean and variance for rolling with advantage in System A and System B.

Let's denote:

$ X_A $ as the random variable representing the outcome of rolling with advantage in System A.

$ X_B $ as the random variable representing the outcome of rolling with advantage in System B.


For System A:
1. Expectation value of the mean:
$$ E[X_A] = \frac{1}{20} \sum_{i=1}^{20} i $$
1. Variance:
$$ Var(X_A) = E[X_A^2] - (E[X_A])^2 $$

For System B:
1. Expectation value of the mean:
$$ E[X_B] = \frac{1}{12} \sum_{i=1}^{12} i + \frac{1}{6} \sum_{i=1}^{6} i $$
2. Variance:
$$ Var(X_B) = E[X_B^2] - (E[X_B])^2 $$



  ### ***Part(2.1(b))***

> Python solution

In [27]:
# FOR A
import numpy as np

# Calculate expectation value of the mean for System A
mean_A = np.mean(np.arange(1, 21))

# Calculate expectation value of the variance for System A
variance_A = np.mean(np.arange(1, 21) ** 2) - mean_A ** 2

mean_A, variance_A


(10.5, 33.25)

In [28]:
# FOR B
import numpy as np

# Calculate expectation value of the mean for System B
mean_B = (np.mean(np.arange(1, 13)) + np.mean(np.arange(1, 7)))

# Calculate expectation value of the variance for System B
variance_B = (np.mean(np.arange(1, 13) ** 2) + np.mean(np.arange(1, 7) ** 2)) - mean_B ** 2

mean_B, variance_B


(10.0, -30.66666666666667)

## ***Question No.  2.2***

In [31]:
import numpy as np

# Number of sides on the dice
num_sides_20 = 20
num_sides_12 = 12

# Simulate rolling with advantage (Event 1)
rolls = np.random.randint(1, num_sides_20 + 1, size=(100000, 2))

# Check if the initial result is less than 6
is_X_lt_6 = np.max(rolls, axis=1) < 6

# If the initial result is less than 6, simulate rolling an extra 12-sided die (Event 2)
num_extra_rolls = np.sum(is_X_lt_6)
extra_rolls = np.random.randint(1, num_sides_12 + 1, size=num_extra_rolls)

# Ensure both arrays have the same shape
is_X_lt_6 = is_X_lt_6[:num_extra_rolls]

# Calculate the probability that Event 1 is X < 6 given that Event 2 is Y = 10
prob_X_lt_6_given_Y_10 = np.mean(is_X_lt_6 & (extra_rolls == 10))

print("Probability of X < 6 given Y = 10:", prob_X_lt_6_given_Y_10)


Probability of X < 6 given Y = 10: 0.004469273743016759


***Explanation:***

- We simulate rolling with advantage (Event 1) by generating two random numbers between 1 and 20 using NumPy.
- We check if the maximum of the two rolls is less than 6, indicating that the initial result is less than 6.
- If the initial result is less than 6, we simulate rolling an extra 12-sided die (Event 2) by generating a ra- ndom number between 1 and 12 using NumPy.
- We calculate the probability that Event 1 is 𝑋 < 6 given that Event 2 is 𝑌 = 10 by taking the mean of the logical AND operation between the conditions for  Event 1 and Event 2.